haproxy:
  image: 'tutum/haproxy:latest'
  environment:
    - BACKEND_PORT=7379
  links:
    - 'webdis'
  ports:
    - '8080:80'
    - '1936:1936'

webdis:
  build: .
  links:
   - 'redis'

redis:
  image: 'redis:latest'
